### ISSUE TITLE
`dla` - log order wrong for historic logs

### ISSUE THREAD

**Issue by MartinRamm** [MartinRamm/fzf-docker#5]
## Which command(s) are affected by the bug?
`dl`, `dla`

## What did you expect to happen?
The output of `dla` is the same as `docker-compose up` (log order is identical)

## What actually happened?
Log order differs:
![image](https://user-images.githubusercontent.com/31626748/53695205-aef3c980-3db8-11e9-85b7-bc5f3736fac2.png)

## Example docker setup
`start`:
```
#!/bin/bash

COUNTER=0
until [ "$COUNTER" -gt 5 ]; do
  echo "$COUNTER"
  let COUNTER+=1
  sleep 1
done
```

`docker-compose.yml`:
```
version: '3'
services:
  first:
    image: ubuntu
    volumes:
    - './start:/start'
    command: bash -c 'chmod +x /start && /start'
  second:
    image: ubuntu
    volumes:
    - './start:/start'
    command: bash -c 'chmod +x /start && /start'
```

## Output of `fzf-docker-debug-info`

```
fzfDockerVersion:
	1.1.1-beta (a71fe0066c159fdbea0754981d27e5c68a08f66e)
shellEnvironment:
	zsh
shellVersion:
	zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
fzfVersion:
	0.17.5 (b46227d)
dockerVersion:
	Docker version 18.09.1, build 4c52b90
dockerComposeVersion:
	docker-compose version 1.23.1, build b02f1306
dockerExecCustomDefaults:
	#!/bin/bash
	
	# Custom defaults for "docker exec"
	# The command to execute should be outputted to stdout. This is optional, so if nothing is outputted the 'normal'
	# defaults will be used.
	# Below is an example implementation
	
	# $1 is the name of the docker image to exec into
	
	_command=''
	
	# image name (without version)
	case $(docker inspect --format '{{.Config.Image}}' $1 | sed -e 's/:.*$//g') in
	
	  "infrastructure_php")
	    _command='sh -c "cd /var/www/lws && bash"'
	
	esac
	
	echo $_command
	unset _command
```
